### ISSUE TITLE
Class tree colors

### ISSUE THREAD

**Issue by chronofreak** [Lothrik/wonderlands-skill-calc#2]
This skill planner is fantastic, thanks for all your work on it. It's looking pretty sharp!

I do miss the different colored borders around each the of the class trees though, which went away a few days ago when the visuals changed to pink and white. Any chance you could bring them back? The different colors were a great way to quickly identify which classes we were looking at.

It would also help if the "progression bar" that extends downward behind the skill boxes as you allocate points was a color and/or value that contrasted more with the background; right now it's hard to distinguish where it is.

**Comment by Lothrik** [comment]
I made the progression bar more obvious by adding a visible border at the bottom edge. I'm not sure exactly how I can address the colored class border request, as I'm not 100% sure what colors I should even use per-class (I was originally using red/green/blue placeholders). I'll come back to this later, hopefully with color ideas and a better solution than just border colors..

**Comment by Lothrik** [comment]
I added a class-colored argyle pattern to the skill trees, hopefully that works. 🙂

**Comment by chronofreak** [comment]
It looks great! Thanks for making the changes. I think the Stabbomancer color is fine, but if you feel like trying a different color I think the Graveborn's dark red would work well, then change Graveborn to gray maybe?

**Comment by Lothrik** [comment]
When I wrote that comment about Stabbomancer it was much closer to brown than the current orange, due to it blending with the purple background. I was trying to make it work without significantly increasing the opacity. It's currently set to ``rgba(255, 127, 0, 0.65)`` when it was previously ``rgba(255, 255, 0, 0.25)``. I might add some color to the action skill buttons, but I think it's fine now. I'll end up reviewing this again at least once more, once the 7th class in DLC4 drops.
